name: yaml-presubmit
on:
  push:
    branches: ['master']
  pull_request:
    paths: ['**.yml', '**.yaml']
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        run: yamllint -d relaxed .
