name: rust-presubmit
on:
  push:
    branches: ['master']
  pull_request:
    paths: ['rust/**', '.github/workflows/presubmit-rust.yml']
  workflow_dispatch: {}

defaults:
  run:
    working-directory: rust

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fmt
        run: cargo fmt --check
      - name: check
        run: cargo check --all-targets --all-features
      - name: clippy
        run: cargo clippy --all-targets --all-features

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --all-targets --all-features
      - name: test
        run: cargo test --all-features
